### ISSUE TITLE
[버그 리포트] 실행 후 로그인(user insert)할 때 에러 발생

### ISSUE THREAD

**Issue by jinc20** [Step3-kakao-tech-campus/Team4_BE#105]
## 버그 설명

    Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.USER_TB(ID) ( /* key:1 */ CAST(2 AS TINYINT), NULL, TRUE, CAST(1         AS BIGINT), 'nstgic@gmail.com', 'FEMALE', 'korean', 'ac98bef6-79c0-4a7b-b9b4-9c3e397dbbd7', NULL, 'KAKAO', '3038773712')"; SQL statement:
    insert into user_tb (age_group,email,email_verified,gender,is_first_login,locale,name,profile_image_url,provider,provider_id,id) values (?,?,?,?,?,?,?,?,?,?,default) [23505-214]

- MatgptApplication을 실행하고 로그인할 때 Unique index or primary key violation 에러가 발생합니다.
- db를 초기화하는 custom.sql 파일과 엔티티 제약조건이 충돌해서 발생한 문제인 것 같습니다.
- 현재 각각의 엔티티는 id의 제약조건으로 IDENTITY가 걸려있어 생성될 때마다 id가 자동 증가하도록 되어 있습니다.
- 그러나 dev 환경에서 사용하고 있는 h2 DB에는 auto increment 기능이 없다고 합니다.
- 프로그램을 실행한 뒤 로그인을 하면 새로운 User 엔티티가 생성되는데, 이때  자동증가가 적용되지 않아 custom.sql의 insert된 user id: 1, 2 insert와 사용자가 로그인하며 생성되는 새로운 User의 id가 충돌하는 것 같습니다.
- weekly 브랜치에서도 같은 문제가 발생하는 것을 확인했습니다.

## 재현 방법
- 프로그램을 실행한 뒤 "http://localhost:8080/oauth2/authorization/kakao"로 접속해 로그인합니다.

## 스크린샷
<img width="355" alt="error-primary-violation1" src="https://github.com/Step3-kakao-tech-campus/Team4_BE/assets/83132869/29f49d56-5662-4fd0-8fe4-0da5953190e6">
<img width="1199" alt="error-primary-violation2" src="https://github.com/Step3-kakao-tech-campus/Team4_BE/assets/83132869/cac3fb5c-94eb-4718-a381-5926d28f8988">

**Comment by nimunsang** [comment]
맞습니다 저도 그래서 두세번 로그인해요ㅋㅋㅋ

**Comment by nimunsang** [comment]
시퀀스 동기화: 더미 데이터를 삽입한 후 데이터베이스의 자동 생성 ID 시퀀스를 더미 데이터의 최대 ID 이상으로 설정합니다.

더미 데이터에 ID 지정하지 않기: 더미 데이터를 삽입할 때 ID 값을 지정하지 않고 데이터베이스에 자동으로 ID를 할당하게 합니다.

GenerationType 변경: GenerationType.IDENTITY 대신 다른 ID 생성 전략을 사용합니다. 예를 들어, GenerationType.SEQUENCE 또는 GenerationType.TABLE과 같은 전략은 데이터베이스의 시퀀스나 별도의 테이블을 사용하여 ID를 관리합니다.


2번 방법이 가장 좋아보이네요

**Comment by ChoMinGi** [comment]
#106 h2를 mysql dialect를 사용하여 문제해결하였습니다.
