### ISSUE TITLE
[기능 요청] ChatGPT API를 사용한 음식점 리스팅에 대한 기능 보완

### ISSUE THREAD

**Issue by nimunsang** [Step3-kakao-tech-campus/Team4_BE#14]
## 기능 요청 개요 및 배경
ChatGPT API를 사용하여 리뷰 5개를 요약한 한 문장을 생성 시, 4초 정도가 걸립니다.
이를 아무리 비동기처리로 뺀다고 해도, 화면을 완성하는데 4초 이상이 걸린다면 사용자들이 매우 불편한 경험을 하게 될 것입니다.

## 요구 사항
- [x] 음식점 한줄 평을 포함한 음식점 리스팅을 구현할 때, 시간이 적게 걸리도록 설계

## 제안하는 해결 방안
1. OneLineReview와 같은 (한줄리뷰) 테이블을 하나 더 설계하여, 주기적(1주일에 1번정도)으로 한줄 리뷰를 ChatGPT API를 통해 받아와서 db에 미리 저장하여 꺼내쓰는 방법 사용
2. (제일 별점이 높은 + 추천 수가 많은) 리뷰 1개를 노출

## 대안
1번 방법이 좋아보이긴 합니다. ChatGPT를 최대한 활용할 수 있으니..

## 관련 이슈
#7

**Comment by ChoMinGi** [comment]
사용자의 이용이 적은 시간대 (새벽)에 업데이트를 해도 좋겠네요.

@nimunsang
추후에 서비스의 규모가 커지게 된다면 고려할 사항이지만 아직으로써는 후순위로 미루어 두는게 좋다고 생각이 드는데 어떻게 생각하시나요?
