### ISSUE TITLE
[기능 요청] 음식점 좋아요 기능

### ISSUE THREAD

**Issue by pigglehyun** [Step3-kakao-tech-campus/Team4_BE#41]
## 기능 요청 개요
사용자는 음식점에 좋아요와 좋아요 취소를 누를 수 있습니다.

## 배경
사용자는 특정 음식점을 좋아요 누르고, 마이페이지에서 좋아요를 누른 음식점 목록을 확인할 수 있습니다.

## 요구 사항
- [x] 1. 좋아요 누르기
  - [x]  POST 요청
  - [x] /stores/{id}/like
  - [x] 특정 음식점 상세 페이지에 들어가 하트를 누르면 좋아요가 눌러진다.
- [x] 2. 좋아요 취소하기
  - [x] DELETE 요청
  - [x] /stores/{id}/like
  - [x] 특정 음식점 상세 페이지에 눌러진 하트를 다시 누르면 좋아요가 취소된다.
- [x] 3. 좋아요 목록 보기
  - [x] GET 요청
  - [x] /mypage/myLike
  - [x] 마이페이지에서 좋아요 목록을 확인할 수 있다.

**관련된 이슈:**

**Comment by ChoMinGi** [comment]
3. 좋아요 목록보기
의 uri 는 /stores/like로 구현되었습니다.

**Comment by pigglehyun** [comment]
> 3. 좋아요 목록보기
>    의 uri 는 /stores/like로 구현되었습니다.

프론트 분들이 마이페이지에서 좋아요 목록 본다고 하셨는데 변경되었나요?
