### ISSUE TITLE
[기능 제안] User Email 자동 주입을 위한 커스텀 어노테이션 및 AOP 도입

### ISSUE THREAD

**Issue by ChoMinGi** [Step3-kakao-tech-campus/Team4_BE#71]
## 기능제안 개요
Oauth2 인증 방식을 사용하며, 보안 상의 이유로 @UserPrincipal에는 회원의 ID 대신 username (이메일)만을 가져오도록 설계되어 있다.
그러나 현재 시스템에서는 많은 API들이 이메일 정보를 사용하여 비즈니스 로직을 처리하고 있다.
이로 인해 매번 @AuthenticationPrincipal 어노테이션을 사용하여 사용자의 이메일 정보를 가져와야 하는 반복적인 작업이 발생하고 있다.

```
@GetMapping("/stores/like")
    public ResponseEntity<?> findAllStores(@AuthenticationPrincipal UserPrincipal userPrincipal){
        LikeStoreResponseDTO.FindAllLikeStoresDTO heartResponseDTO = likeStoreService.findStoresByUserEmail(userPrincipal.getEmail());
        ApiUtils.ApiSuccess<?> apiResult = ApiUtils.success(heartResponseDTO);
        return ResponseEntity.ok(apiResult);

    }
```

이를 해결하기 위해, 커스텀 AOP와 커스텀 어노테이션을 도입하여 사용자의 이메일 정보를 자동으로 주입받을 수 있게 제안한다.

## 제안할 해결책
@UserEmailPrincipal이라는 커스텀 어노테이션을 생성한다. 해당 어노테이션은 메소드의 파라미터로 사용될 것이다.
AOP를 이용하여 @UserEmailPrincipal어노테이션을 포함한 메소드가 호출될 때, UserPrincipal에서 이메일 정보를 가져와 메소드의 파라미터로 자동 주입한다.

### 예시
```
@GetMapping("/stores/like")
public ResponseEntity<?> findAllStores(@UserEmail String userEmail) {
    LikeStoreResponseDTO.FindAllLikeStoresDTO heartResponseDTO = likeStoreService.findStoresByUserEmail(userEmail);
    ApiUtils.ApiSuccess<?> apiResult = ApiUtils.success(heartResponseDTO);
    return ResponseEntity.ok(apiResult);
}
```

## 장점
- 반복적인 코드 줄임으로서 코드의 가독성과 유지 보수성이 향상된다.
- AOP를 통한 중복 코드 제거는 애플리케이션의 일관성을 높이고 에러 가능성을 줄인다.
- 향후 추가되는 API에서도 이메일 정보를 쉽게 가져와 사용할 수 있다.

## 단점
- AOP를 도입함으로써 애플리케이션의 실행 흐름을 파악하기 어려워질 수 있다.
- 잘못 구현하는 경우 성능에 문제가 생길수도 있다.

## 요약
보안상의 이유로 이메일 정보만을 사용하는 현재의 시스템 구조에서, 커스텀 AOP와 어노테이션을 도입하여 코드의 중복성을 줄이고 효율성을 높이는 방안을 제안한다.

## 백로그 정보
**예상 작업 시간:** 1일

**Comment by ChoMinGi** [comment]
@nimunsang 
@jinc20 
@pigglehyun 
 Comment 남겨주시면 감사하겠습니다!

**Comment by pigglehyun** [comment]
주의해서 잘 사용하면 정말 편리할거 같네요 !! 수고하셨습니다 👍👍
